CREATE TABLE IF NOT EXISTS Origins.Origins
(
	Id uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL UNIQUE,
	Name VARCHAR(500) NOT NULL,
	Alias VARCHAR(200) NOT NULL UNIQUE,
	Type SMALLINT NOT NULL,
	SystemCreated BOOLEAN NOT NULL,
	CreationDate TIMESTAMP NOT NULL,
	LastUpdateDate TIMESTAMP NULL,
	LastUpdateUser VARCHAR(255) NULL,
	MajorVersion SMALLINT NOT NULL,
	MinorVersion SMALLINT NOT NULL,
	PathVersion SMALLINT NOT NULL,
	ChangeReason VARCHAR NOT NULL
);
